### ISSUE TITLE
Systsem3 no longer works

### ISSUE THREAD

**Issue by RashadGasimly** [wr3cckl3ss/system3#6]
Helllo, I used system3 shell until August security patch, but it's no longerworking. Is there any things with root for downgrade system apps??
![Screenshot_20231221_145908_InstallerX](https://github.com/wr3cckl3ss1/system3/assets/129990317/eb7bef08-96c4-4f57-a406-8e425788e7ec)
![Screenshot_20231221_145818](https://github.com/wr3cckl3ss1/system3/assets/129990317/149c55f6-3166-4535-a689-d20f898a6297)

**Comment by wr3cckl3ss1** [comment]
@RashadGasimly

I'm quite unsure of what you're asking me. 
Are you asking if you can root?
Asking how to downgrade?
And if you have root....why are you trying to use FTL, root is greater than FTL?
Lastly what device, do you currently have and what firmware?

**Comment by RashadGasimly** [comment]
> @RashadGasimly
> 
> I'm quite unsure of what you're asking me. 
> Are you asking if you can root?
> Asking how to downgrade?
> And if you have root....why are you trying to use FTL, root is greater than FTL?
> Lastly what device, do you currently have and what firmware?
> 

Yes i have root but however i can't downgrade with root 💀 it says #3001 error. If you know how bypass this sht with root please tell me

**Comment by wr3cckl3ss1** [comment]
Message me on Telegram.

**Comment by RashadGasimly** [comment]
> Message me on Telegram.
what is your telegram,sir

**Comment by wr3cckl3ss1** [comment]
t.me/wr3cckl3ss

**Comment by RashadGasimly** [comment]
I wrote you

**Comment by wr3cckl3ss1** [comment]
What's your name?

**Comment by RashadGasimly** [comment]
> What's your name?

@RashadGasimly

**Comment by RashadGasimly** [comment]
in telegram ofc

**Comment by RashadGasimly** [comment]
![Screenshot (97)](https://github.com/wr3cckl3ss1/system3/assets/129990317/a266e5ed-547d-41e7-b65d-221148fe4236)

**Comment by wr3cckl3ss1** [comment]
I don't see you..at all.

**Comment by wr3cckl3ss1** [comment]
@rashadgasimov

**Comment by wr3cckl3ss1** [comment]
I sent you a message

**Comment by camellan** [comment]
What if you try this? "pm install -r -d -f -g --full --install-reason 3 --enable-rollback"

**Comment by wr3cckl3ss1** [comment]
@camellan Google very recently....decided to kill all downgradomg.. including USER apps....there are certain exemptions. But nothing.....a system or shell user can do.

That command is from SMT. And what's even more interesting....none that was ever needed at all

pm install -r -d -f -g --full --install-reason 3 --enable-rollback

A simple...

pm install -d

🤣🤣🤣🤣

**Comment by camellan** [comment]
> @camellan Google very recently....decided to kill all downgradomg.. including USER apps....there are certain exemptions. But nothing.....a system or shell user can do.
> 
> That command is from SMT. And what's even more interesting....none that was ever needed at all
> 
> pm install -r -d -f -g --full --install-reason 3 --enable-rollback
> 
> A simple...
> 
> pm install -d
> 
> 🤣🤣🤣🤣

👍😂
