### ISSUE TITLE
Security patch update 1 sep, 2023. OneUI 5.1

### ISSUE THREAD

**Issue by sauvikbp** [wr3cckl3ss/system3#8]
Does it work on Samsung A52s 5G?
Security Patch Update: September 1, 2023
One UI 5.1, Android Version 13

Thanks for the awesome project. I just want my band selection back 😩

**Comment by wr3cckl3ss** [comment]
I hope that you ultimately meant good by opening up an issue here when you could of found me on two different social platforms to ask. Or you could of just browsed around for the answers. And to be fair, if that's all you really want. Then there's plenty that you can do after you realize that this has limited support pursuant that you can meet a downgrade method, for your band needs. If you don't have anymore questions. I will close this out completely.

**Comment by sauvikbp** [comment]
Thanks 😊
